name: Bump version
on:
  push:
    branches:
      - main
      - main-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run build on 'action' folder
        run: |
          cd action && npm run build
      - name: Bump version and push tag
        id: tag_version
        uses: ./action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main-test
          dry_run: true
      - name: Create a GitHub release
        uses: actions/create-release@v1
        if: ${{ !env.ACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
